language: node_js
node_js: '7'
install: npm install
notifications:
  email: false
  slack:
    bons:KZl1tUMPIYFg8Ev8AlZf19bo
    on_success:never
    on_failure:change
services:
- mongodb
- redis-server
before_install:
- sudo apt-get install python-software-properties
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install gcc-5 g++-5
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++
  g++ /usr/bin/g++-5
- sudo update-alternatives --set gcc /usr/bin/gcc-5
before_script:
- sleep 10
- mongo mydb_test --eval 'db.addUser("travis", "test");'
